[project]
name = "torch-state-bridge"
version = "0.1.0"
description = "Rename State Dictionary Keys"
readme = "README.md"
authors = [
    { name = "dummyjenil", email = "dummyjenil@gmail.com" }
]
dependencies = []

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
